name: 👋 Help Request
description: What can the community help with
title: "[Help Request]: "
labels: ["help wanted"]
assignees:
  - Celerium
body:
  - type: checkboxes
    id: ReadME
    attributes:
      label: Project README
      description: "[Project README](https://github.com/Celerium/Celerium-PowerShell/blob/master/README.md)"
      options:
        - label: "Have you read the projects README?"
  - type: checkboxes
    id: WebDocumentation
    attributes:
      label: Online Documentation
      description: "[Online Documentation](https://Celerium.github.io/Celerium/)"
      options:
        - label: "Have you read the online documentation"
  - type: textarea
    id: HelpRequest
    attributes:
      label: Help Request
      description: What would you like help with?
      render: Text
  - type: textarea
    id: ExistingIssue
    attributes:
      label: Existing Issue?
      description: Is this related to an existing issue? If so please describe or link.
      value: "Issue: #12345"