#
# Module manifest for module 'Celerium'
#
# Generated by: David Schulte
#
# Generated on: 2025-02-25
#

@{

    # Script module or binary module file associated with this manifest
    # RootModule = 'Celerium.psm1'

    # Version number of this module.
    ModuleVersion = '1.3.0'

    # ID used to uniquely identify this module
    GUID = 'c1b1c1e0-0ba5-4c69-bd92-393d69d10a62'

    # Author of this module
    Author = 'David Schulte'

    # Company or vendor of this module
    CompanyName = 'Celerium'

    # Description of the functionality provided by this module
    Description = 'Celerium PowerShell - A collection of modules, functions, scripts, and more to help automate, audit, and manage your IT environment.'

    # Copyright information of this module
    Copyright = 'https://github.com/Celerium/Celerium-PowerShell/blob/master/LICENSE'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of the .NET Framework required by this module
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @(
        @{ ModuleName = 'Celerium.Auvik';       ModuleVersion = '1.1.0'; Guid = 'c4624e25-e787-48eb-a8d5-a4c8e287412f' },
        @{ ModuleName = 'Celerium.ITGlue';      ModuleVersion = '1.0.0'; Guid = 'ce707f0f-1969-4192-a08b-80f62be28f2f' },
        @{ ModuleName = 'Celerium.RocketCyber'; ModuleVersion = '1.0.0'; Guid = 'cba0c431-1670-43d7-a2db-4ab683da7dcb' }
    )

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @()

    # Cmdlets to export from this module
    CmdletsToExport = @()

    # Variables to export from this module
    # VariablesToExport = @()

    # Aliases to export from this module
    AliasesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess.
    PrivateData = @{
        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('API', 'PowerShell', 'Windows', 'MacOS', 'Linux', 'PSEdition_Desktop', 'PSEdition_Core', 'Celerium')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/Celerium/Celerium-PowerShell/blob/master/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Celerium/Celerium-PowerShell'

            # A URL to an icon representing this module.
            IconUri = 'https://raw.githubusercontent.com/Celerium/Celerium-PowerShell/refs/heads/main/.github/images/PoSHGallery_PowerShell.png'

            # ReleaseNotes of this module
            ReleaseNotes = 'https://github.com/Celerium/Celerium-PowerShell/blob/master/README.md'

            # Identifies the module as a prerelease version in online galleries.
            #PreRelease = '-BETA'

            # Indicate whether the module requires explicit user acceptance for install, update, or save.
            RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
